/*
 * minigraphics in-development (versioned releases will come later)
 *
 * NOTE: minigraphics uses an indentifier called 'mg' and identifiers
 * beginning with 'mg__' or 'MG__' internally; using these may cause
 * conflicts.
 *
 * ===========================================================================
 * LICENSE
 *
 * see the end of the file for license information.
 *
 * ===========================================================================
 * USAGE
 *
 * if you are planning to use the Wayland backend, read the
 * "WAYLAND PROTOCOLS" section below.
 *
 * include this header wherever you need it as usual. in ONE file, add:
 * 	#define MG_IMPLEMENTATION
 * before the #include for this header.
 *
 * additionally, you'll need to define ONE of these macros:
 * 	#define MG_BACKEND_X11
 * 	#define MG_BACKEND_WAYLAND
 * to use one of the respective backends. the same backend must be defined in
 * ANY file that includes this header.
 *
 * to make the implementation private to the file that generates it, also add:
 * 	#define MG_STATIC
 *
 * by default, __attribute__((__unused__)) is used if __GNUC__ is defined;
 * you can override this by defining MG_UNUSED to some value to be used
 * instead of the attribute, or setting it to an empty value:
 * 	#define MG_UNUSED
 *
 * see the "DOCS" section for the API documentation.
 * see the examples directory for example programs.
 *
 * ===========================================================================
 * WAYLAND PROTOCOLS
 *
 * if you are planning to use the Wayland backend, you'll need the header
 * "xdg-shell-client-protocol.h" in the same directory as this header,
 * AND you'll need to add "xdg-shell-protocol.c" to your sources.
 *
 * to generate these files, make sure you have wayland-protocols and
 * wayland-scanner (typically provided by a package named 'wayland' or
 * 'wayland-devel') installed and then run:
 *
 * wayland-scanner private-code \
 * 		< /usr/share/wayland-protocols/stable/xdg-shell/xdg-shell.xml \
 * 		> xdg-shell-protocol.c
 *
 * wayland-scanner client-header \
 * 		< /usr/share/wayland-protocols/stable/xdg-shell/xdg-shell.xml \
 * 		> xdg-shell-client-protocol.h
 */
#if !defined(MG_H)
#define MG_H
#include <setjmp.h>
#include <stdint.h>

#include <xkbcommon/xkbcommon-keysyms.h>

#if !defined(MG_BACKEND_X11) && !defined(MG_BACKEND_WAYLAND)
#error please define a backend for minigraphics.
#elif defined(MG_BACKEND_X11) && defined(MG_BACKEND_WAYLAND)
#error only one backend may be defined.
#elif defined(MG_BACKEND_X11)
#include <X11/Xlib.h>
#endif

#if defined(MG_STATIC)
#define MG__DEF static
#else
#define MG__DEF extern
#endif /* defined(MG_STATIC) */

#if !defined(MG_UNUSED)

#if defined(__GNUC__)
#define MG_UNUSED __attribute__((__unused__))
#else
#define MG_UNUSED
#endif /* defined(__GNUC__) */

#if defined(MG_BACKEND_X11)
struct mg_image {
	XImage *ximage;
	Pixmap pixmap;
	uint32_t width, height;
};
#elif defined(MG_BACKEND_WAYLAND)
struct mg_image {
	uint8_t *data;
	uint32_t width, height;
};
#endif /* defined(MG_BACKEND_X11) || defined(MG_BACKEND_WAYLAND) */

#endif /* !defined(MG_UNUSED) */

/*
 * ===========================================================================
 * DOCS (+ header)
 *
 * these global variables hold the current window dimensions and are updated
 * automatically whenever it is resized.
 */
extern int mg_width;
extern int mg_height;
/* these are all of the errors that can be generated by this library. */
enum mg_error {
	MG_INIT_FAILED,
	MG_OUT_OF_MEMORY,
	MG_UNSUPPORTED_COLOR_DEPTH,
	MG_UNSUPPORTED_KEYMAP
};
/*
 * this global variable holds the error type if the library encounters an
 * error (for more info, see below, at mg_init())
 */
extern enum mg_error mg_errno;
/*
 * minigraphics uses an event loop for handling of things such as
 * key presses, mouse clicks/movement, etc.
 * these are all of the possible events that can be recieved.
 */
enum mg_event_type {
	MG_NOEVENT,    /* used internally, never reported */
	MG_QUIT,       /* user has requested to close the window */
	MG_RESIZE,     /* window has been resized */
	MG_REDRAW,     /* window should be redrawn */
	MG_KEYDOWN,    /* a key on the keyboard has been pressed */
	MG_KEYUP,      /* a key on the keyboard has been unpressed */
	MG_MOUSEDOWN,  /* a button on the mouse has been pressed */
	MG_MOUSEUP,    /* a button on the mouse has been unpressed */
	MG_MOUSEMOTION /* the mouse has moved */
};
/* a mouse button is represented one of the following values: */
enum mg_mouse_btn {
	MG_MOUSE_NO_BUTTON, /* used internally, never reported */
	MG_MOUSE_LEFT,
	MG_MOUSE_MIDDLE,
	MG_MOUSE_RIGHT,
	MG_MOUSE_SIDE,
	MG_MOUSE_EXTRA
};
/*
 * when an event is recieved (see below on how they are recieved), it
 * is stored in a structure with the following layout:
 */
struct mg_event {
	/* event type */
	enum mg_event_type type;

	/*
	 * XKB keysym for the key -- if 'type' is not MG_KEYDOWN or
	 * MG_KEYUP, the value of this field is undefined.
	 */
	uint32_t key;

	/*
	 * mouse button -- if 'type' is not MG_MOUSEDOWN or MG_MOUSEUP,
	 * the value of this field is undefined.
	 */
	enum mg_mouse_btn button;

	/*
	 * X and Y position of the mouse cursor -- if 'type' is not
	 * MG_MOUSEMOTION, the values of these fields are undefined.
	 */
	int x;		   /* mouse cursor X position */
	int y;		   /* mouse cursor Y position */
};
/*
 * now, for the functions.
 *
 * before doing anything with the library, you must initialize it by calling:
 */
MG__DEF void mg_init(int w, int h, const char *title, jmp_buf err_return);
/*
 * the 'w' and 'h' parameters specify the requested size for the window -- the
 * actual width and height might be different and will be stored in the
 * mg_width and mg_height variables.
 *
 * the 'title' parameter specifies the requested title for the window.
 *
 * the 'err_return' parameter must be a valid jmp_buf initialized by a call to
 * setjmp(). if an error is ever encountered, a longjmp() to there occurs;
 * you can use the variable 'mg_errno' to determine what error occurred.
 *
 * to convert that variable into an error message, use:
 */
MG__DEF const char *mg_strerror(enum mg_error err);
/*
 * once you are ready to quit, call:
 */
MG__DEF void mg_quit(void);
/*
 * to exit the library; this will close the window. do not call this if
 * you are exiting due to a library error.
 *
 * to recieve an event, you can call:
 */
MG__DEF int mg_getevent(struct mg_event *event);
/*
 * 'event' must be a valid pointer to a mg_event structure; the event
 * data will be stored inside this structure. if no events are
 * currently pending, 0 is returned; otherwise, 1 is returned.
 *
 * alternatively, you can call:
 */
MG__DEF void mg_waitevent(struct mg_event *event);
/*
 * which will block until an event is recieved and store the event data
 * inside the structure pointed to by 'event'.
 *
 * to draw things on the window, use one of the following functions:
 */

/* clear everything on the window with the current background color. */
MG__DEF void mg_clear(void);

/*
 * draw an outline of a circle using the current drawing color,
 * with its middle point being located at (x, y) and its radius being 'r'.
 */
MG__DEF void mg_drawcircle(int x, int y, int r);

/*
 * draw a line from the point (x1, y1) to the point (x2, y2) using the
 * current drawing color.
 */
MG__DEF void mg_drawline(int x1, int y1, int x2, int y2);

/* draw a pixel at the point (x, y) using the current drawing color. */
MG__DEF void mg_drawpixel(int x, int y);

/*
 * draw an outline of a rectangle using the current drawing color,
 * with its top-left point being located at (x1, y1) and its bottom-left
 * point being at (x2, y2).
 */
MG__DEF void mg_drawrect(int x1, int y1, int x2, int y2);

/*
 * draw a string in an 8x8 bitmap font using the current drawing color,
 * with the top-left corner of the first 8x8 character box being at (x, y).
 * the 'size' parameter specifies the font size, so a 'size' of 2 will draw
 * 16x16 text.
 */
MG__DEF void mg_drawtext(int x, int y, const char *text, int size);

/*
 * draw an outline of a triangle with the current drawing color,
 * with its vertices being at the points (x1, y1), (x2, y2), and (x3, y3).
 */
MG__DEF void mg_drawtriangle(int x1, int y1, int x2, int y2, int x3, int y3);

/*
 * draw a filled-in circle using the current drawing color,
 * with its middle point being located at (x, y) and its radius being 'r'.
 */
MG__DEF void mg_fillcircle(int x, int y, int r);

/*
 * draw a filled-in rectangle using the current drawing color,
 * with its top-left point being located at (x1, y1) and its bottom-left
 * point being at (x2, y2).
 */
MG__DEF void mg_fillrect(int x1, int y1, int x2, int y2);

/*
 * draw a filled-in triangle with the current drawing color,
 * with its vertice
 * return img;s being at the points (x1, y1), (x2, y2), and (x3, y3).
 */
MG__DEF void mg_filltriangle(int x1, int y1, int x2, int y2, int x3, int y3);

/*
 * commit all changes to the window -- calling this is necessary to be
 * 100% sure your changes are actually displayed on the window.
 */
MG__DEF void mg_flush(void);

/*
 * the following functions can be used to draw images:
 *
 * create an image from the memory buffer 'data', which should contain valid
 * RGB data, with each pixel being represented by three values.
 * 'width' and 'height' specify the image's width and height in pixels.
 *
 * if 'width' does not match image's width or 'height' is larger than
 * the image's height, the behaviour is undefined.
 *
 * if either 'width' or 'height' are zero, a NULL pointer is returned.
 *
 * the memory buffer referenced by the 'data' field is copied and changes
 * to it after the image creation will not affect the image. for example,
 * if 'data' is a dynamically allocated object, it can be freed after the
 * call to mg_image_create().
 */
MG__DEF struct mg_image *mg_image_create(uint8_t *data, uint32_t width, uint32_t height);

/*
 * draw an image with the location of the top-left corner being (x, y).
 * if 'image' is a NULL pointer, nothing is drawn.
 */
MG__DEF void mg_image_draw(struct mg_image *image, int x, int y);

/*
 * free the memory allocated for an image. attempting to use this image
 * again is undefined behaviour.
 * if 'image' is a NULL pointer, nothing is done.
 */
MG__DEF void mg_image_free(struct mg_image *image);

/*
 * to change the colors used by the mg_draw/mg_fill functions, use one of
 * the following:
 *
 * set the current background color to the color specified by the
 * RGB value (r, g, b).
 * the default is (255, 255, 255) (white).
 */
MG__DEF void mg_setbgcolor(uint8_t r, uint8_t g, uint8_t b);

/*
 * set the current drawing color to the color specified by the
 * RGB value (r, g, b).
 * the default is (0, 0, 0) (black).
 */
MG__DEF void mg_setdrawcolor(uint8_t r, uint8_t g, uint8_t b);

/* end of docs/header */

#endif /* !defined(MG_H) */

/*
 * ===========================================================================
 * IMPLEMENTATION
 */
#if defined(MG_IMPLEMENTATION)

/*
 * ===========================================================================
 * CONSTANTS
 */
static const unsigned char mg__font[95][8] = {
	/* make sure that (c >= 0x20 && c <= 0x7e) */
	{ 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}, /* U+0020 (space) */
	{ 0x18, 0x3C, 0x3C, 0x18, 0x18, 0x00, 0x18, 0x00}, /* U+0021 (!) */
	{ 0x36, 0x36, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}, /* U+0022 (") */
	{ 0x36, 0x36, 0x7F, 0x36, 0x7F, 0x36, 0x36, 0x00}, /* U+0023 (#) */
	{ 0x0C, 0x3E, 0x03, 0x1E, 0x30, 0x1F, 0x0C, 0x00}, /* U+0024 ($) */
	{ 0x00, 0x63, 0x33, 0x18, 0x0C, 0x66, 0x63, 0x00}, /* U+0025 (%) */
	{ 0x1C, 0x36, 0x1C, 0x6E, 0x3B, 0x33, 0x6E, 0x00}, /* U+0026 (&) */
	{ 0x06, 0x06, 0x03, 0x00, 0x00, 0x00, 0x00, 0x00}, /* U+0027 (') */
	{ 0x18, 0x0C, 0x06, 0x06, 0x06, 0x0C, 0x18, 0x00}, /* U+0028 (() */
	{ 0x06, 0x0C, 0x18, 0x18, 0x18, 0x0C, 0x06, 0x00}, /* U+0029 ()) */
	{ 0x00, 0x66, 0x3C, 0xFF, 0x3C, 0x66, 0x00, 0x00}, /* U+002A (*) */
	{ 0x00, 0x0C, 0x0C, 0x3F, 0x0C, 0x0C, 0x00, 0x00}, /* U+002B (+) */
	{ 0x00, 0x00, 0x00, 0x00, 0x00, 0x0C, 0x0C, 0x06}, /* U+002C (,) */
	{ 0x00, 0x00, 0x00, 0x3F, 0x00, 0x00, 0x00, 0x00}, /* U+002D (-) */
	{ 0x00, 0x00, 0x00, 0x00, 0x00, 0x0C, 0x0C, 0x00}, /* U+002E (.) */
	{ 0x60, 0x30, 0x18, 0x0C, 0x06, 0x03, 0x01, 0x00}, /* U+002F (/) */
	{ 0x3E, 0x63, 0x73, 0x7B, 0x6F, 0x67, 0x3E, 0x00}, /* U+0030 (0) */
	{ 0x0C, 0x0E, 0x0C, 0x0C, 0x0C, 0x0C, 0x3F, 0x00}, /* U+0031 (1) */
	{ 0x1E, 0x33, 0x30, 0x1C, 0x06, 0x33, 0x3F, 0x00}, /* U+0032 (2) */
	{ 0x1E, 0x33, 0x30, 0x1C, 0x30, 0x33, 0x1E, 0x00}, /* U+0033 (3) */
	{ 0x38, 0x3C, 0x36, 0x33, 0x7F, 0x30, 0x78, 0x00}, /* U+0034 (4) */
	{ 0x3F, 0x03, 0x1F, 0x30, 0x30, 0x33, 0x1E, 0x00}, /* U+0035 (5) */
	{ 0x1C, 0x06, 0x03, 0x1F, 0x33, 0x33, 0x1E, 0x00}, /* U+0036 (6) */
	{ 0x3F, 0x33, 0x30, 0x18, 0x0C, 0x0C, 0x0C, 0x00}, /* U+0037 (7) */
	{ 0x1E, 0x33, 0x33, 0x1E, 0x33, 0x33, 0x1E, 0x00}, /* U+0038 (8) */
	{ 0x1E, 0x33, 0x33, 0x3E, 0x30, 0x18, 0x0E, 0x00}, /* U+0039 (9) */
	{ 0x00, 0x0C, 0x0C, 0x00, 0x00, 0x0C, 0x0C, 0x00}, /* U+003A (:) */
	{ 0x00, 0x0C, 0x0C, 0x00, 0x00, 0x0C, 0x0C, 0x06}, /* U+003B (;) */
	{ 0x18, 0x0C, 0x06, 0x03, 0x06, 0x0C, 0x18, 0x00}, /* U+003C (<) */
	{ 0x00, 0x00, 0x3F, 0x00, 0x00, 0x3F, 0x00, 0x00}, /* U+003D (=) */
	{ 0x06, 0x0C, 0x18, 0x30, 0x18, 0x0C, 0x06, 0x00}, /* U+003E (>) */
	{ 0x1E, 0x33, 0x30, 0x18, 0x0C, 0x00, 0x0C, 0x00}, /* U+003F (?) */
	{ 0x3E, 0x63, 0x7B, 0x7B, 0x7B, 0x03, 0x1E, 0x00}, /* U+0040 (@) */
	{ 0x0C, 0x1E, 0x33, 0x33, 0x3F, 0x33, 0x33, 0x00}, /* U+0041 (A) */
	{ 0x3F, 0x66, 0x66, 0x3E, 0x66, 0x66, 0x3F, 0x00}, /* U+0042 (B) */
	{ 0x3C, 0x66, 0x03, 0x03, 0x03, 0x66, 0x3C, 0x00}, /* U+0043 (C) */
	{ 0x1F, 0x36, 0x66, 0x66, 0x66, 0x36, 0x1F, 0x00}, /* U+0044 (D) */
	{ 0x7F, 0x46, 0x16, 0x1E, 0x16, 0x46, 0x7F, 0x00}, /* U+0045 (E) */
	{ 0x7F, 0x46, 0x16, 0x1E, 0x16, 0x06, 0x0F, 0x00}, /* U+0046 (F) */
	{ 0x3C, 0x66, 0x03, 0x03, 0x73, 0x66, 0x7C, 0x00}, /* U+0047 (G) */
	{ 0x33, 0x33, 0x33, 0x3F, 0x33, 0x33, 0x33, 0x00}, /* U+0048 (H) */
	{ 0x1E, 0x0C, 0x0C, 0x0C, 0x0C, 0x0C, 0x1E, 0x00}, /* U+0049 (I) */
	{ 0x78, 0x30, 0x30, 0x30, 0x33, 0x33, 0x1E, 0x00}, /* U+004A (J) */
	{ 0x67, 0x66, 0x36, 0x1E, 0x36, 0x66, 0x67, 0x00}, /* U+004B (K) */
	{ 0x0F, 0x06, 0x06, 0x06, 0x46, 0x66, 0x7F, 0x00}, /* U+004C (L) */
	{ 0x63, 0x77, 0x7F, 0x7F, 0x6B, 0x63, 0x63, 0x00}, /* U+004D (M) */
	{ 0x63, 0x67, 0x6F, 0x7B, 0x73, 0x63, 0x63, 0x00}, /* U+004E (N) */
	{ 0x1C, 0x36, 0x63, 0x63, 0x63, 0x36, 0x1C, 0x00}, /* U+004F (O) */
	{ 0x3F, 0x66, 0x66, 0x3E, 0x06, 0x06, 0x0F, 0x00}, /* U+0050 (P) */
	{ 0x1E, 0x33, 0x33, 0x33, 0x3B, 0x1E, 0x38, 0x00}, /* U+0051 (Q) */
	{ 0x3F, 0x66, 0x66, 0x3E, 0x36, 0x66, 0x67, 0x00}, /* U+0052 (R) */
	{ 0x1E, 0x33, 0x07, 0x0E, 0x38, 0x33, 0x1E, 0x00}, /* U+0053 (S) */
	{ 0x3F, 0x2D, 0x0C, 0x0C, 0x0C, 0x0C, 0x1E, 0x00}, /* U+0054 (T) */
	{ 0x33, 0x33, 0x33, 0x33, 0x33, 0x33, 0x3F, 0x00}, /* U+0055 (U) */
	{ 0x33, 0x33, 0x33, 0x33, 0x33, 0x1E, 0x0C, 0x00}, /* U+0056 (V) */
	{ 0x63, 0x63, 0x63, 0x6B, 0x7F, 0x77, 0x63, 0x00}, /* U+0057 (W) */
	{ 0x63, 0x63, 0x36, 0x1C, 0x1C, 0x36, 0x63, 0x00}, /* U+0058 (X) */
	{ 0x33, 0x33, 0x33, 0x1E, 0x0C, 0x0C, 0x1E, 0x00}, /* U+0059 (Y) */
	{ 0x7F, 0x63, 0x31, 0x18, 0x4C, 0x66, 0x7F, 0x00}, /* U+005A (Z) */
	{ 0x1E, 0x06, 0x06, 0x06, 0x06, 0x06, 0x1E, 0x00}, /* U+005B ([) */
	{ 0x03, 0x06, 0x0C, 0x18, 0x30, 0x60, 0x40, 0x00}, /* U+005C (\) */
	{ 0x1E, 0x18, 0x18, 0x18, 0x18, 0x18, 0x1E, 0x00}, /* U+005D (]) */
	{ 0x08, 0x1C, 0x36, 0x63, 0x00, 0x00, 0x00, 0x00}, /* U+005E (^) */
	{ 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xFF}, /* U+005F (_) */
	{ 0x0C, 0x0C, 0x18, 0x00, 0x00, 0x00, 0x00, 0x00}, /* U+0060 (`) */
	{ 0x00, 0x00, 0x1E, 0x30, 0x3E, 0x33, 0x6E, 0x00}, /* U+0061 (a) */
	{ 0x07, 0x06, 0x06, 0x3E, 0x66, 0x66, 0x3B, 0x00}, /* U+0062 (b) */
	{ 0x00, 0x00, 0x1E, 0x33, 0x03, 0x33, 0x1E, 0x00}, /* U+0063 (c) */
	{ 0x38, 0x30, 0x30, 0x3e, 0x33, 0x33, 0x6E, 0x00}, /* U+0064 (d) */
	{ 0x00, 0x00, 0x1E, 0x33, 0x3f, 0x03, 0x1E, 0x00}, /* U+0065 (e) */
	{ 0x1C, 0x36, 0x06, 0x0f, 0x06, 0x06, 0x0F, 0x00}, /* U+0066 (f) */
	{ 0x00, 0x00, 0x6E, 0x33, 0x33, 0x3E, 0x30, 0x1F}, /* U+0067 (g) */
	{ 0x07, 0x06, 0x36, 0x6E, 0x66, 0x66, 0x67, 0x00}, /* U+0068 (h) */
	{ 0x0C, 0x00, 0x0E, 0x0C, 0x0C, 0x0C, 0x1E, 0x00}, /* U+0069 (i) */
	{ 0x30, 0x00, 0x30, 0x30, 0x30, 0x33, 0x33, 0x1E}, /* U+006A (j) */
	{ 0x07, 0x06, 0x66, 0x36, 0x1E, 0x36, 0x67, 0x00}, /* U+006B (k) */
	{ 0x0E, 0x0C, 0x0C, 0x0C, 0x0C, 0x0C, 0x1E, 0x00}, /* U+006C (l) */
	{ 0x00, 0x00, 0x33, 0x7F, 0x7F, 0x6B, 0x63, 0x00}, /* U+006D (m) */
	{ 0x00, 0x00, 0x1F, 0x33, 0x33, 0x33, 0x33, 0x00}, /* U+006E (n) */
	{ 0x00, 0x00, 0x1E, 0x33, 0x33, 0x33, 0x1E, 0x00}, /* U+006F (o) */
	{ 0x00, 0x00, 0x3B, 0x66, 0x66, 0x3E, 0x06, 0x0F}, /* U+0070 (p) */
	{ 0x00, 0x00, 0x6E, 0x33, 0x33, 0x3E, 0x30, 0x78}, /* U+0071 (q) */
	{ 0x00, 0x00, 0x3B, 0x6E, 0x66, 0x06, 0x0F, 0x00}, /* U+0072 (r) */
	{ 0x00, 0x00, 0x3E, 0x03, 0x1E, 0x30, 0x1F, 0x00}, /* U+0073 (s) */
	{ 0x08, 0x0C, 0x3E, 0x0C, 0x0C, 0x2C, 0x18, 0x00}, /* U+0074 (t) */
	{ 0x00, 0x00, 0x33, 0x33, 0x33, 0x33, 0x6E, 0x00}, /* U+0075 (u) */
	{ 0x00, 0x00, 0x33, 0x33, 0x33, 0x1E, 0x0C, 0x00}, /* U+0076 (v) */
	{ 0x00, 0x00, 0x63, 0x6B, 0x7F, 0x7F, 0x36, 0x00}, /* U+0077 (w) */
	{ 0x00, 0x00, 0x63, 0x36, 0x1C, 0x36, 0x63, 0x00}, /* U+0078 (x) */
	{ 0x00, 0x00, 0x33, 0x33, 0x33, 0x3E, 0x30, 0x1F}, /* U+0079 (y) */
	{ 0x00, 0x00, 0x3F, 0x19, 0x0C, 0x26, 0x3F, 0x00}, /* U+007A (z) */
	{ 0x38, 0x0C, 0x0C, 0x07, 0x0C, 0x0C, 0x38, 0x00}, /* U+007B ({) */
	{ 0x18, 0x18, 0x18, 0x00, 0x18, 0x18, 0x18, 0x00}, /* U+007C (|) */
	{ 0x07, 0x0C, 0x0C, 0x38, 0x0C, 0x0C, 0x07, 0x00}, /* U+007D (}) */
	{ 0x6E, 0x3B, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}, /* U+007E (~) */
};

static const char *mg__strerrors[] = {
	"library initialization failed",
	"out of memory",
	"unsupported color depth",
	"unsupported keymap"
};

/*
 * ===========================================================================
 * X11 BACKEND
 */
#if defined(MG_BACKEND_X11)
#include <stdlib.h>
#include <string.h>

/* #include <X11/Xlib.h> (already included in the header) */
#include <X11/XKBlib.h>
#include <X11/Xutil.h>

/* macros */
#define MG__ERROR(errno) { mg_errno = errno; longjmp(mg.err_return, 1); }
#define MG__MIN(x, y) ((x < y) ? x : y)
#define MG__X_EVENT_MASK ExposureMask | StructureNotifyMask | KeyPressMask | \
	KeyReleaseMask | ButtonPressMask | ButtonReleaseMask

/* types */
struct mg__state {
	int screen;
	Display *dpy;
	Window root, win;
	Atom wmdeletewin;
	GC gc;
	Colormap colormap;
	unsigned int depth;

	unsigned long black, white;
	unsigned long bgcolor, color;

	int closed;

	jmp_buf err_return;
};

/* global variables */
static struct mg__state mg;

int mg_width;
int mg_height;
enum mg_error mg_errno;

/* internal functions */
static int
mg__handle_x_event(struct mg_event *event, XEvent *xevnt)
{
	static int pressed = 0;
	static unsigned int lastkeycode;
	switch (xevnt->type) {
	case ClientMessage:
		/* we got a message */
		if ((Atom)xevnt->xclient.data.l[0] == mg.wmdeletewin) {
			event->type = MG_QUIT;
			return 1;
		}
		break;
	case ConfigureNotify:
		/* the window has changed somehow */
		if (xevnt->xconfigure.width != mg_width || xevnt->xconfigure.height != mg_height) {
			mg_width = xevnt->xconfigure.width;
			mg_height = xevnt->xconfigure.height;
			event->type = MG_RESIZE;
			return 1;
		}
		break;
	case Expose:
		event->type = MG_REDRAW;
		return 1;
	case KeyPress:
		if (pressed && xevnt->xkey.keycode == lastkeycode) {
			lastkeycode = xevnt->xkey.keycode;
			break;
		}
		pressed = 1;
		lastkeycode = xevnt->xkey.keycode;
		event->key = (uint32_t)XLookupKeysym(&xevnt->xkey, 0);
		event->type = MG_KEYDOWN;
		return 1;
	case KeyRelease:
		if (pressed && xevnt->xkey.keycode == lastkeycode)
			pressed = 0;
		event->key = (uint32_t)XLookupKeysym(&xevnt->xkey, 0);
		event->type = MG_KEYUP;
		return 1;
	case ButtonPress:
		if (xevnt->xbutton.x >= 0 && xevnt->xbutton.y >= 0) {
			enum mg_mouse_btn button;
			int set = 0;
			switch (xevnt->xbutton.button) {
			case 1:
				button = MG_MOUSE_LEFT;
				set = 1;
				break;
			case 2:
				button = MG_MOUSE_MIDDLE;
				set = 1;
				break;
			case 3:
				button = MG_MOUSE_RIGHT;
				set = 1;
				break;
			case 8:
				button = MG_MOUSE_SIDE;
				set = 1;
				break;
			case 9:
				button = MG_MOUSE_EXTRA;
				set = 1;
				break;
			}
			if (set) {
				event->button = button;
				event->type = MG_MOUSEDOWN;
				return 1;
			}
		}
		break;
	case ButtonRelease:
		if (xevnt->xbutton.x >= 0 && xevnt->xbutton.y >= 0) {
			enum mg_mouse_btn button;
			int set = 0;
			switch (xevnt->xbutton.button) {
			case 1:
				button = MG_MOUSE_LEFT;
				set = 1;
				break;
			case 2:
				button = MG_MOUSE_MIDDLE;
				set = 1;
				break;
			case 3:
				button = MG_MOUSE_RIGHT;
				set = 1;
				break;
			case 8:
				button = MG_MOUSE_SIDE;
				set = 1;
				break;
			case 9:
				button = MG_MOUSE_EXTRA;
				set = 1;
				break;
			}
			if (set) {
				event->button = button;
				event->type = MG_MOUSEUP;
				return 1;
			}
		}
		break;
	case MotionNotify:
		if (xevnt->xmotion.x >= 0 && xevnt->xmotion.y >= 0) {
			Window dummy1, dummy2;
			int dummy3, dummy4;
			unsigned int dummy5;

			int x, y;

			if (XQueryPointer(mg.dpy, mg.win, &dummy1, &dummy2, &dummy3,
						&dummy4, &x, &y, &dummy5)) {
				if (x >= 0 && y >= 0 && (event->x != x || event->y != y)) {
					event->x = x;
					event->y = y;
					event->type = MG_MOUSEMOTION;
					return 1;
				}
			}
		}
		break;
	}
	return 0;
}

/* initialization, shutdown, and errors */
void
mg_init(int w, int h, const char *title, jmp_buf err_return)
{
	XEvent xevnt;

	*mg.err_return = *err_return;

	/* open display */
	if (!(mg.dpy = XOpenDisplay(NULL)))
		MG__ERROR(MG_INIT_FAILED)

	/* set detectable autorepeat */
	XkbSetDetectableAutoRepeat(mg.dpy, True, NULL);

	/* set screen, root window, colormap, and background color */
	mg.screen = DefaultScreen(mg.dpy);
	mg.root = DefaultRootWindow(mg.dpy);
	mg.colormap = DefaultColormap(mg.dpy, mg.screen);
	mg.depth = (unsigned int)DefaultDepth(mg.dpy, mg.screen);
	mg.bgcolor = mg.white = WhitePixel(mg.dpy, mg.screen);
	mg.color = mg.black = BlackPixel(mg.dpy, mg.screen);

	/* create window */
	mg.win = XCreateSimpleWindow(mg.dpy, mg.root, 0, 0,
			(unsigned int)w, (unsigned int)h, 0, mg.bgcolor, mg.bgcolor);
	mg.closed = 0;
	mg_width = w;
	mg_height = h;

	/* name our window */
	XStoreName(mg.dpy, mg.win, title);

	/* specify WM_DELETE_WINDOW protocol */
	mg.wmdeletewin = XInternAtom(mg.dpy, "WM_DELETE_WINDOW", 1);
	XSetWMProtocols(mg.dpy, mg.win, &mg.wmdeletewin, 1);

	/* tell X what events we are interested in */
	XSelectInput(mg.dpy, mg.win, MG__X_EVENT_MASK | PointerMotionMask);

	/* map window */
	XMapWindow(mg.dpy, mg.win);

	/* create graphics context */
	mg.gc = XCreateGC(mg.dpy, mg.win, 0, NULL);

	/* set GC colors */
	XSetBackground(mg.dpy, mg.gc, mg.bgcolor);
	XSetWindowBackground(mg.dpy, mg.win, mg.bgcolor);
	XSetForeground(mg.dpy, mg.gc, mg.color);

	/* wait for window mapping */
	for (;;) {
		XNextEvent(mg.dpy, &xevnt);
		if (xevnt.type == ConfigureNotify) {
			mg_width = xevnt.xconfigure.width;
			mg_height = xevnt.xconfigure.height;
		} else if (xevnt.type == MapNotify) {
			break;
		}
	}
}

const char *
mg_strerror(enum mg_error err)
{
	return mg__strerrors[err];
}

void
mg_quit(void)
{
	if (!mg.closed) {
		XFreeGC(mg.dpy, mg.gc);
		XDestroyWindow(mg.dpy, mg.win);
		XCloseDisplay(mg.dpy);
		mg.closed = 1;
	}
}

/* events */
int
mg_getevent(struct mg_event *event)
{
	/* this is kinda boiletplate-y but i cant figure out a better solution... */
	XEvent xevnt;

	if (XCheckTypedEvent(mg.dpy, ClientMessage, &xevnt))
		/* check for clientmessage events first */
		if (mg__handle_x_event(event, &xevnt))
			return 1;
	if (XCheckWindowEvent(mg.dpy, mg.win, MG__X_EVENT_MASK, &xevnt))
		/*
		 * MotionNotify events in xlib are kinda weird and completely clog up
		 * the event queue, so check if we have any non-pointer-motion events
		 */
		if (mg__handle_x_event(event, &xevnt))
			return 1;
	if (XCheckWindowEvent(mg.dpy, mg.win, MG__X_EVENT_MASK | PointerMotionMask, &xevnt))
		/* if not, throw in pointer events too */
		if (mg__handle_x_event(event, &xevnt))
			return 1;
	return 0;
}

void
mg_waitevent(struct mg_event *event)
{
	XEvent xevnt;
	for (;;) {
		/* wait for an X event to happen */
		XNextEvent(mg.dpy, &xevnt);

		/* handle event */
		if (mg__handle_x_event(event, &xevnt))
			break;
	}
}

/* drawing functions */
void
mg_clear(void)
{
	XClearWindow(mg.dpy, mg.win);
}

void 
mg_drawcircle(int x, int y, int r)
{
	XDrawArc(mg.dpy, mg.win, mg.gc, x - r, y - r, (unsigned int)r * 2, (unsigned int)r * 2, 0, 360 * 64);
}

void
mg_drawline(int x1, int y1, int x2, int y2)
{
	XDrawLine(mg.dpy, mg.win, mg.gc, x1, y1, x2, y2);
}

void
mg_drawpixel(int x, int y)
{
	XDrawPoint(mg.dpy, mg.win, mg.gc, x, y);
}

void
mg_drawrect(int x1, int y1, int x2, int y2)
{
	XDrawRectangle(mg.dpy, mg.win, mg.gc, MG__MIN(x1, x2), MG__MIN(y1, y2),
			(unsigned int)abs(x2 - x1), (unsigned int)abs(y2 - y1));
}

void
mg_drawtext(int x, int y, const char *text, int size)
{
	size_t i;
	int points = 0;
	int px, py; /* point x, point y */
	int dx = 0; /* draw x */
	size_t len = strlen(text);
	if (size == 1) {
		XPoint letter[64];
		Pixmap pixmap = XCreatePixmap(mg.dpy, mg.win, (unsigned int)(len * 8), 8, mg.depth);
		XSetForeground(mg.dpy, mg.gc, mg.bgcolor);
		XFillRectangle(mg.dpy, pixmap, mg.gc, 0, 0, (unsigned int)(len * 8), 8);
		XSetForeground(mg.dpy, mg.gc, mg.color);

		for (i = 0; i < len; ++i) {
			for (py = 0; py < 8; ++py) {
				for (px = 0; px < 8; ++px) {
					if (text[i] >= 0x20 && text[i] <= 0x7e &&
							(mg__font[text[i] - 0x20][py] & 1 << px)) {
						letter[points].x = (short)(dx + px);
						letter[points].y = (short)py;
						++points;
					}
				}
			}
			dx += 8;
			if (points)
				XDrawPoints(mg.dpy, pixmap, mg.gc, letter, points, CoordModeOrigin);
			points = 0;
		}

		XCopyArea(mg.dpy, pixmap, mg.win, mg.gc, 0, 0, (unsigned int)len * 8, 8, x, y);
		XFreePixmap(mg.dpy, pixmap);
	} else if (size > 1) {
		XRectangle letter[64];
		Pixmap pixmap = XCreatePixmap(mg.dpy, mg.win, (unsigned int)(len * 8 * (size_t)size),
				(unsigned int)(8 * size), mg.depth);
		XSetForeground(mg.dpy, mg.gc, mg.bgcolor);
		XFillRectangle(mg.dpy, pixmap, mg.gc, 0, 0, (unsigned int)(len * 8 * (size_t)size),
				(unsigned int)(8 * size));
		XSetForeground(mg.dpy, mg.gc, mg.color);

		for (i = 0; i < len; ++i) {
			for (py = 0; py < 8; ++py) {
				for (px = 0; px < 8; ++px) {
					if (text[i] >= 0x20 && text[i] <= 0x7e &&
							(mg__font[text[i] - 0x20][py] & 1 << px)) {
						letter[points].x = (short)(dx + (px * size));
						letter[points].y = (short)(py * size);
						letter[points].width = (unsigned short)size;
						letter[points].height = (unsigned short)size;
						++points;
					}
				}
			}
			dx += 8 * size;
			if (points)
				XFillRectangles(mg.dpy, pixmap, mg.gc, letter, points);
			points = 0;
		}

		XCopyArea(mg.dpy, pixmap, mg.win, mg.gc, 0, 0, (unsigned int)(len * 8 * (size_t)size),
				(unsigned int)(8 * size), x, y);
		XFreePixmap(mg.dpy, pixmap);
	}
}

void
mg_drawtriangle(int x1, int y1, int x2, int y2, int x3, int y3)
{
	XDrawLine(mg.dpy, mg.win, mg.gc, x1, y1, x2, y2);
	XDrawLine(mg.dpy, mg.win, mg.gc, x2, y2, x3, y3);
	XDrawLine(mg.dpy, mg.win, mg.gc, x3, y3, x1, y1);
}

void
mg_fillcircle(int x, int y, int r)
{
	XFillArc(mg.dpy, mg.win, mg.gc, x - r, y - r, (unsigned int)r * 2, (unsigned int)r * 2, 0, 360 * 64);
}

void
mg_fillrect(int x1, int y1, int x2, int y2)
{
	XFillRectangle(mg.dpy, mg.win, mg.gc, MG__MIN(x1, x2), MG__MIN(y1, y2),
			(unsigned int)abs(x2 - x1), (unsigned int)abs(y2 - y1));
}

void
mg_filltriangle(int x1, int y1, int x2, int y2, int x3, int y3)
{
	XPoint points[3];
	points[0].x = (short)x1;
	points[0].y = (short)y1;
	points[1].x = (short)x2;
	points[1].y = (short)y2;
	points[2].x = (short)x3;
	points[2].y = (short)y3;
	XFillPolygon(mg.dpy, mg.win, mg.gc, points, 3, Convex, CoordModeOrigin);
}

void
mg_flush(void)
{
	XFlush(mg.dpy);
}

/* images */
struct mg_image *
mg_image_create(uint8_t *data, uint32_t width, uint32_t height)
{
	if (width == 0 || height == 0)
		return NULL;

	if (mg.depth >= 24) {
		struct mg_image *img = malloc(sizeof(struct mg_image));
		size_t i = 0, j = 0, k = 0;

		if (!img)
			MG__ERROR(MG_OUT_OF_MEMORY)
		img->pixmap = XCreatePixmap(mg.dpy, mg.win, width, height, mg.depth);
		img->ximage = XCreateImage(mg.dpy, CopyFromParent, mg.depth, ZPixmap, 0, NULL, width, height,
				32, (int)(width * 4));
		img->ximage->data = malloc(width * height * 4);
		if (!img->ximage->data)
			MG__ERROR(MG_OUT_OF_MEMORY)

		for (; i < width * height; ++i) {
			img->ximage->data[k] = (char)(data[j + 2]);
			img->ximage->data[k + 1] = (char)(data[j + 1]);
			img->ximage->data[k + 2] = (char)(data[j]);
			j += 3;
			k += 4;
		}

		XInitImage(img->ximage);

		img->width = width;
		img->height = height;

		return img;
	}
	MG__ERROR(MG_UNSUPPORTED_COLOR_DEPTH)
}

void
mg_image_draw(struct mg_image *image, int x, int y)
{
	if (!image)
		return;

	XSetForeground(mg.dpy, mg.gc, mg.bgcolor);
	XFillRectangle(mg.dpy, image->pixmap, mg.gc, 0, 0, image->width, image->height);
	XSetForeground(mg.dpy, mg.gc, mg.color);
	XPutImage(mg.dpy, image->pixmap, mg.gc, image->ximage, 0, 0, 0, 0, image->width, image->height);
	XCopyArea(mg.dpy, image->pixmap, mg.win, mg.gc, 0, 0, image->width, image->height, x, y);
}

void
mg_image_free(struct mg_image *image)
{
	if (!image)
		return;

	XDestroyImage(image->ximage);
	XFreePixmap(mg.dpy, image->pixmap);
	free(image);
}

/* functions to set colors */
void
mg_setbgcolor(uint8_t r, uint8_t g, uint8_t b)
{
	static int unfreed = 0;

	if (unfreed) {
		XFreeColors(mg.dpy, mg.colormap, &mg.bgcolor, 1, 0);
		unfreed = 0;
	}

	if (r == 0 && g == 0 && b == 0) {
		mg.bgcolor = mg.black;
	} else if (r == 25 && g == 255 && b == 255) {
		mg.bgcolor = mg.white;
	} else {
		XColor color;
		color.red = r * 257;
		color.green = g * 257;
		color.blue = b * 257;

		unfreed = 1;
		XAllocColor(mg.dpy, mg.colormap, &color);
		mg.bgcolor = color.pixel;
	}
	XSetBackground(mg.dpy, mg.gc, mg.bgcolor);
	XSetWindowBackground(mg.dpy, mg.win, mg.bgcolor);
}

void
mg_setdrawcolor(uint8_t r, uint8_t g, uint8_t b)
{
	static int unfreed = 0;

	if (unfreed) {
		XFreeColors(mg.dpy, mg.colormap, &mg.color, 1, 0);
		unfreed = 0;
	}

	if (r == 0 && g == 0 && b == 0) {
		mg.color = mg.black;
	} else if (r == 25 && g == 255 && b == 255) {
		mg.color = mg.white;
	} else {
		XColor color;
		color.red = r * 257;
		color.green = g * 257;
		color.blue = b * 257;

		unfreed = 1;
		XAllocColor(mg.dpy, mg.colormap, &color);
		mg.color = color.pixel;
	}
	XSetForeground(mg.dpy, mg.gc, mg.color);
}
#endif /* defined(MG_BACKEND_X11) */

/*
 * ===========================================================================
 * WAYLAND BACKEND
 */
#if defined(MG_BACKEND_WAYLAND)

#if _POSIX_C_SOURCE < 200112L
#undef _POSIX_C_SOURCE
#define _POSIX_C_SOURCE 200112L
#endif /* _POSIX_C_SOURCE < 200112L */

#if defined(__linux__)
#include <linux/input-event-codes.h>
#else
#define BTN_MOUSE  0x110
#define BTN_LEFT   0x110
#define BTN_RIGHT  0x111
#define BTN_MIDDLE 0x112
#define BTN_SIDE   0x113
#define BTN_EXTRA  0x114
#endif /* defined(__linux__) */

#include <sys/mman.h>

#include <errno.h>
#include <fcntl.h>
#include <limits.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <unistd.h>

#include <wayland-client.h>
#include <xkbcommon/xkbcommon.h>

#include "xdg-shell-client-protocol.h"

/* macros */
#define MG__ERROR(errno) { mg_errno = errno; longjmp(mg.err_return, 1); }
#define MG__MIN(x, y) (((x) < (y)) ? (x) : (y))
#define MG__MAX(x, y) (((x) > (y)) ? (x) : (y))
#define MG__PIXELSET(x, y) \
	if ((x) >= 0 && (y) >= 0 && (x) < (int)mg.buf_width && (y) < (int)mg.buf_height) \
		mg.draw_buf[(y) * (int)mg.buf_width + (x)] = mg.color
#define MG__PIXELSET_NOBOUNDSCHECK(x, y) \
	mg.draw_buf[(y) * (int)mg.buf_width + (x)] = mg.color

/* types */
enum mg__pointer_event_mask {
	MG__POINTER_EVENT_ENTER = 1 << 0,
	MG__POINTER_EVENT_LEAVE = 1 << 1,
	MG__POINTER_EVENT_MOTION = 1 << 2,
	MG__POINTER_EVENT_BUTTON = 1 << 3,
	MG__POINTER_EVENT_AXIS = 1 << 4,
	MG__POINTER_EVENT_AXIS_SOURCE = 1 << 5,
	MG__POINTER_EVENT_AXIS_STOP = 1 << 6,
	MG__POINTER_EVENT_AXIS_DISCRETE = 1 << 7,
};

struct mg__pointer_event {
	uint32_t event_mask;
	wl_fixed_t surface_x, surface_y;
	uint32_t button, state;
	uint32_t time;
	uint32_t serial;
	struct {
		int valid;
		wl_fixed_t value;
		int32_t discrete;
	} axes[2];
	uint32_t axis_source;
};

struct mg__state {
	/* globals */
	struct wl_display *wl_display;
	struct wl_registry *wl_registry;
	struct wl_shm *wl_shm;
	struct wl_compositor *wl_compositor;
	struct xdg_wm_base *xdg_wm_base;
	struct wl_seat *wl_seat;
	/* objects */
	struct wl_surface *wl_surface;
	struct xdg_surface *xdg_surface;
	struct wl_keyboard *wl_keyboard;
	struct wl_pointer *wl_pointer;
	struct wl_touch *wl_touch;
	struct xdg_toplevel *xdg_toplevel;
	/* state */
	int configured;
	struct mg__pointer_event mg_pointer_event;
	struct xkb_state *xkb_state;
	struct xkb_context *xkb_context;
	struct xkb_keymap *xkb_keymap;

	int closed;
	uint32_t *draw_buf;
	uint32_t bgcolor, color;
	size_t buf_width, buf_height, buf_stride, buf_size;

	/* highest to lowest priority */
	int pending_quit;
	int pending_resize;
	uint32_t pending_key_down;
	uint32_t pending_key_up;
	enum mg_mouse_btn pending_mouse_down;
	enum mg_mouse_btn pending_mouse_up;
	int pending_mouse_motion_x, pending_mouse_motion_y;

	jmp_buf err_return;
};

/* global variables */
static struct mg__state mg;

int mg_width;
int mg_height;
enum mg_error mg_errno;

/* internal utility functions */
static int
mg__clamp(int val, int min, int max)
{
	if (val < min)
		return min;
	else if (val > max)
		return max;
	else
		return val;
}

static void
mg__fillflatsidetriangle(int x1, int y1, int x2, int y2, int x3, int y3)
{
	/* points 2 and 3 must be on the same horizontal line (y2 == y3) */
	int tmp1_x = x1, tmp1_y = y1;
	int tmp2_x = x1, tmp2_y = y1;

	int changed1 = 0, changed2 = 0;

	int dx1 = abs(x2 - x1);
	int dy1 = abs(y2 - y1);

	int dx2 = abs(x3 - x1);
	int dy2 = abs(y3 - y1);

	int sx1 = (x2 - x1 > 0) ? 1 : -1;
	int sx2 = (x3 - x1 > 0) ? 1 : -1;

	int sy1 = (y2 - y1 > 0) ? 1 : -1;
	int sy2 = (y3 - y1 > 0) ? 1 : -1;

	int e1, e2;

	int i, tmp;
	int lowx, highx;

	if (dy1 > dx1) {
		tmp = dx1;
		dx1 = dy1;
		dy1 = tmp;
		changed1 = 1;
	}

	if (dy2 > dx2) {
		tmp = dx2;
		dx2 = dy2;
		dy2 = tmp;
		changed2 = 1;
	}

	e1 = 2 * dy1 - dx1;
	e2 = 2 * dy2 - dx2;

	for (i = 0; i <= dx1; ++i) {
		/* mg_drawline(tmp1_x, tmp1_y, tmp2_x, tmp2_y); */

		if (tmp1_y >= 0 && tmp1_y < (int)mg.buf_height) {
			/* assuming tmp1_y == tmp2_y */
			lowx = mg__clamp(MG__MIN(tmp1_x, tmp2_x), 0, (int)mg.buf_width - 1);
			highx = mg__clamp(MG__MAX(tmp1_x, tmp2_x), 0, (int)mg.buf_width - 1);
			for (; lowx <= highx; ++lowx)
				MG__PIXELSET_NOBOUNDSCHECK(lowx, tmp1_y);
		}

		while (e1 >= 0) {
			if (changed1)
				tmp1_x += sx1;
			else
				tmp1_y += sy1;
			e1 = e1 - 2 * dx1;
		}

		if (changed1)
			tmp1_y += sy1;
		else
			tmp1_x += sx1;

		e1 = e1 + 2 * dy1;

		while (tmp2_y != tmp1_y) {
			while (e2 >= 0) {
				if (changed2)
					tmp2_x += sx2;
				else
					tmp2_y += sy2;
				e2 = e2 - 2 * dx2;
			}

			if (changed2)
				tmp2_y += sy2;
			else
				tmp2_x += sx2;

			e2 = e2 + 2 * dy2;
		}
	}
}

static void
mg__frametrimcpy(uint32_t *dst, const uint32_t *src, size_t oldwidth, size_t newwidth,
		size_t oldstride, size_t newstride, size_t oldheight, size_t newheight)
{
	size_t roff = 0, woff = 0;
	size_t stride = MG__MIN(oldstride, newstride);
	size_t i = 0;
	for (; i < MG__MIN(oldheight, newheight) &&
			(roff < oldwidth * oldheight) &&
			(woff < newwidth * newheight); ++i) {
		memcpy(dst + woff, src + roff, stride);
		roff += oldwidth;
		woff += newwidth;
	}
}

static int
mg__handle_wl_event(struct mg_event *event)
{
	if (mg.pending_quit) {
		event->type = MG_QUIT;
		mg.pending_quit = 0;
		return 1;
	} else if (mg.pending_resize) {
		event->type = MG_RESIZE;
		mg.pending_resize = 0;
		return 1;
	} else if (mg.pending_key_down) {
		event->type = MG_KEYDOWN;
		event->key = mg.pending_key_down;
		mg.pending_key_down = 0;
		return 1;
	} else if (mg.pending_key_up) {
		event->type = MG_KEYUP;
		event->key = mg.pending_key_up;
		mg.pending_key_up = 0;
		return 1;
	} else if (mg.pending_mouse_down != MG_MOUSE_NO_BUTTON) {
		event->type = MG_MOUSEDOWN;
		event->button = mg.pending_mouse_down;
		mg.pending_mouse_down = MG_MOUSE_NO_BUTTON;
		return 1;
	} else if (mg.pending_mouse_up != MG_MOUSE_NO_BUTTON) {
		event->type = MG_MOUSEUP;
		event->button = mg.pending_mouse_up;
		mg.pending_mouse_up = MG_MOUSE_NO_BUTTON;
		return 1;
	} else if (mg.pending_mouse_motion_x >= 0) {
		event->type = MG_MOUSEMOTION;
		event->x = mg.pending_mouse_motion_x;
		event->y = mg.pending_mouse_motion_y;
		mg.pending_mouse_motion_x = -1;
		mg.pending_mouse_motion_y = -1;
		return 1;
	}
	return 0;
}

static void
mg__sort_ascending_by_y(int x1, int y1, int x2, int y2, int x3, int y3,
		int *nx1, int *ny1, int *nx2, int *ny2, int *nx3, int *ny3)
{
#define MG__SWAP(x, y) tmp = x; x = y; y = tmp;
	int tmp;
	if (y1 > y3) {
		MG__SWAP(y1, y3);
		MG__SWAP(x1, x3);
	}
	if (y1 > y2) {
		MG__SWAP(y1, y2);
		MG__SWAP(x1, x2);
	}
	if (y2 > y3) {
		MG__SWAP(y2, y3);
		MG__SWAP(x2, x3);
	}
#undef MG__SWAP

	/* remember that lower Y value = higher */
	*nx1 = x3;
	*ny1 = y3;
	*nx2 = x2;
	*ny2 = y2;
	*nx3 = x1;
	*ny3 = y1;
}

/* shared memory stuff */
static void
mg__randname(char *buf)
{
	/* generate a (pretty bad) random filename. */
	struct timespec ts;
	long r;
	clock_gettime(CLOCK_REALTIME, &ts);
	r = ts.tv_nsec;
	for (int i = 0; i < 6; ++i) {
		buf[i] = (char)('A'+(r&15)+(r&16)*2);
		r >>= 5;
	}
}

static int
mg__create_shm_file(void)
{
	int retries = 100;
	int fd;
	do {
		char name[] = "/mg-wl_shm-XXXXXX";
		mg__randname(name + sizeof(name) - 7);
		retries--;
		fd = shm_open(name, O_RDWR | O_CREAT | O_EXCL, 0600);
		if (fd >= 0) {
			shm_unlink(name);
			return fd;
		}
	} while (retries > 0 && errno == EEXIST);
	return -1;
}

static int
mg__allocate_shm_file(size_t size)
{
	int fd = mg__create_shm_file();
	int ret;
	if (fd < 0)
		return -1;
	do {
		/*
		 * despite what it sounds like, ftruncate can
		 * actually increase the size of the file,
		 * that's what we're doing here
		 */
		ret = ftruncate(fd, (off_t)size);
	} while (ret < 0 && errno == EINTR);
	if (ret < 0) {
		close(fd);
		return -1;
	}
	return fd;
}

/* wayland event handling */
static void
mg__wl_pointer_enter(void *data, MG_UNUSED struct wl_pointer *wl_pointer, uint32_t serial,
		MG_UNUSED struct wl_surface *surface, wl_fixed_t surface_x, wl_fixed_t surface_y)
{
	/* pointer entered our surface */
	struct mg__state *mg_state = (struct mg__state *)data;
	mg_state->mg_pointer_event.event_mask |= MG__POINTER_EVENT_ENTER;
	mg_state->mg_pointer_event.serial = serial;
	mg_state->mg_pointer_event.surface_x = surface_x;
	mg_state->mg_pointer_event.surface_y = surface_y;
}

static void
mg__wl_pointer_leave(void *data, MG_UNUSED struct wl_pointer *wl_pointer, uint32_t serial,
		MG_UNUSED struct wl_surface *surface)
{
	/* pointer left our surface */
	struct mg__state *mg_state = (struct mg__state *)data;
	mg_state->mg_pointer_event.serial = serial;
	mg_state->mg_pointer_event.event_mask |= MG__POINTER_EVENT_LEAVE;
}

static void
mg__wl_pointer_motion(void *data, MG_UNUSED struct wl_pointer *wl_pointer, uint32_t time,
		wl_fixed_t surface_x, wl_fixed_t surface_y)
{
	struct mg__state *mg_state = (struct mg__state *)data;
	mg_state->mg_pointer_event.event_mask |= MG__POINTER_EVENT_MOTION;
	mg_state->mg_pointer_event.time = time;
	mg_state->mg_pointer_event.surface_x = surface_x;
	mg_state->mg_pointer_event.surface_y = surface_y;
}

static void
mg__wl_pointer_button(void *data, MG_UNUSED struct wl_pointer *wl_pointer, uint32_t serial,
		uint32_t time, uint32_t button, uint32_t state)
{
	struct mg__state *mg_state = (struct mg__state *)data;
	mg_state->mg_pointer_event.event_mask |= MG__POINTER_EVENT_BUTTON;
	mg_state->mg_pointer_event.time = time;
	mg_state->mg_pointer_event.serial = serial;
	mg_state->mg_pointer_event.button = button;
	mg_state->mg_pointer_event.state = state;
}

static void
mg__wl_pointer_axis(void *data, MG_UNUSED struct wl_pointer *wl_pointer, uint32_t time, uint32_t axis,
		wl_fixed_t value)
{
	struct mg__state *mg_state = (struct mg__state *)data;
	mg_state->mg_pointer_event.event_mask |= MG__POINTER_EVENT_AXIS;
	mg_state->mg_pointer_event.time = time;
	mg_state->mg_pointer_event.axes[axis].valid = 1;
	mg_state->mg_pointer_event.axes[axis].value = value;
}

static void
mg__wl_pointer_axis_source(void *data, MG_UNUSED struct wl_pointer *wl_pointer, uint32_t axis_source)
{
	struct mg__state *mg_state = (struct mg__state *)data;
	mg_state->mg_pointer_event.event_mask |= MG__POINTER_EVENT_AXIS_SOURCE;
	mg_state->mg_pointer_event.axis_source = axis_source;
}

static void
mg__wl_pointer_axis_stop(void *data, MG_UNUSED struct wl_pointer *wl_pointer, uint32_t time,
		uint32_t axis)
{
	struct mg__state *mg_state = (struct mg__state *)data;
	mg_state->mg_pointer_event.time = time;
	mg_state->mg_pointer_event.event_mask |= MG__POINTER_EVENT_AXIS_STOP;
	mg_state->mg_pointer_event.axes[axis].valid = 1;
}

static void
mg__wl_pointer_axis_discrete(void *data, MG_UNUSED struct wl_pointer *wl_pointer, uint32_t axis,
		int32_t discrete)
{
	struct mg__state *mg_state = (struct mg__state *)data;
	mg_state->mg_pointer_event.event_mask |= MG__POINTER_EVENT_AXIS_DISCRETE;
	mg_state->mg_pointer_event.axes[axis].valid = 1;
	mg_state->mg_pointer_event.axes[axis].discrete = discrete;
}

static void
mg__wl_pointer_frame(void *data, MG_UNUSED struct wl_pointer *wl_pointer)
{
	/* some pointer event happened, this is where we handle these */
	struct mg__state *mg_state = (struct mg__state *)data;
	struct mg__pointer_event *event = &mg_state->mg_pointer_event;

	if ((event->event_mask & MG__POINTER_EVENT_ENTER) ||
			(event->event_mask & MG__POINTER_EVENT_MOTION)) {
		mg_state->pending_mouse_motion_x = wl_fixed_to_int(event->surface_x);
		mg_state->pending_mouse_motion_y = wl_fixed_to_int(event->surface_y);
	}

	if (event->event_mask & MG__POINTER_EVENT_BUTTON && event->button >= BTN_LEFT &&
			event->button <= BTN_EXTRA) {
		enum mg_mouse_btn button;
		int set = 0;
		switch (event->button) {
		case BTN_LEFT:
			button = MG_MOUSE_LEFT;
			set = 1;
			break;
		case BTN_MIDDLE:
			button = MG_MOUSE_MIDDLE;
			set = 1;
			break;
		case BTN_RIGHT:
			button = MG_MOUSE_RIGHT;
			set = 1;
			break;
		case BTN_SIDE:
			button = MG_MOUSE_SIDE;
			set = 1;
			break;
		case BTN_EXTRA:
			button = MG_MOUSE_EXTRA;
			set = 1;
			break;
		}
		if (set) {
			if (event->state == WL_POINTER_BUTTON_STATE_PRESSED)
				mg_state->pending_mouse_down = button;
			else
				mg_state->pending_mouse_up = button;
		}
	}

	memset(event, 0, sizeof(*event));
}

static const struct wl_pointer_listener mg__wl_pointer_listener = {
	.enter = mg__wl_pointer_enter,
	.leave = mg__wl_pointer_leave,
	.motion = mg__wl_pointer_motion,
	.button = mg__wl_pointer_button,
	.axis = mg__wl_pointer_axis,
	.frame = mg__wl_pointer_frame,
	.axis_source = mg__wl_pointer_axis_source,
	.axis_stop = mg__wl_pointer_axis_stop,
	.axis_discrete = mg__wl_pointer_axis_discrete,
};

/* keyboard */
static void
mg__wl_keyboard_keymap(void *data, MG_UNUSED struct wl_keyboard *wl_keyboard, uint32_t format,
		int32_t fd, uint32_t size)
{
	struct mg__state *mg_state = (struct mg__state *)data;
	char *map_shm;
	struct xkb_keymap *xkb_keymap;
	struct xkb_state *xkb_state;

	if (format != WL_KEYBOARD_KEYMAP_FORMAT_XKB_V1)
		MG__ERROR(MG_UNSUPPORTED_KEYMAP)

	if ((map_shm = mmap(NULL, size, PROT_READ, MAP_SHARED, fd, 0)) == MAP_FAILED)
		MG__ERROR(MG_OUT_OF_MEMORY)

	/* configure the keymap */
	xkb_keymap = xkb_keymap_new_from_string(mg_state->xkb_context, map_shm,
			XKB_KEYMAP_FORMAT_TEXT_V1, XKB_KEYMAP_COMPILE_NO_FLAGS);
	munmap(map_shm, size);
	close(fd);

	xkb_state = xkb_state_new(xkb_keymap);
	xkb_keymap_unref(mg_state->xkb_keymap);
	xkb_state_unref(mg_state->xkb_state);
	mg_state->xkb_keymap = xkb_keymap;
	mg_state->xkb_state = xkb_state;
}

static void
mg__wl_keyboard_enter(MG_UNUSED void *data, MG_UNUSED struct wl_keyboard *wl_keyboard, MG_UNUSED uint32_t serial,
		MG_UNUSED struct wl_surface *surface, MG_UNUSED struct wl_array *keys)
{
	/* TODO: fire MG_KEYDOWN event for each key */
	/*
	struct mg__state *mg_state = (struct mg__state *)data;
	fputs("keyboard enter; keys pressed are:\n", stderr);
	uint32_t *key;
	wl_array_for_each(key, keys) {
		char buf[128];
		xkb_keysym_t sym = xkb_state_key_get_one_sym(
				mg_state->xkb_state, *key + 8);
		xkb_keysym_get_name(sym, buf, sizeof(buf));
		fprintf(stderr, "sym: %-12s (%d), ", buf, sym);
		xkb_state_key_get_utf8(mg_state->xkb_state,
				*key + 8, buf, sizeof(buf));
		fprintf(stderr, "utf8: '%s'\n", buf);
	}
	*/
}

static void
mg__wl_keyboard_key(void *data, MG_UNUSED struct wl_keyboard *wl_keyboard, MG_UNUSED uint32_t serial,
		MG_UNUSED uint32_t time, uint32_t key, uint32_t state)
{
	/* key press/release event */
	struct mg__state *mg_state = (struct mg__state *)data;
	if (state == WL_KEYBOARD_KEY_STATE_PRESSED)
		mg_state->pending_key_down = xkb_state_key_get_one_sym(mg_state->xkb_state, key + 8);
	else
		mg_state->pending_key_up = xkb_state_key_get_one_sym(mg_state->xkb_state, key + 8);
}

static void
mg__wl_keyboard_leave(MG_UNUSED void *data,
		MG_UNUSED struct wl_keyboard *wl_keyboard,
		MG_UNUSED uint32_t serial,
		MG_UNUSED struct wl_surface *surface)
{
	/*fputs("keyboard leave\n", stderr);*/
}

static void
mg__wl_keyboard_modifiers(void *data, MG_UNUSED struct wl_keyboard *wl_keyboard,
		MG_UNUSED uint32_t serial, uint32_t mods_depressed, uint32_t mods_latched,
		uint32_t mods_locked, uint32_t group)
{
	struct mg__state *mg_state = (struct mg__state *)data;
	xkb_state_update_mask(mg_state->xkb_state,
			mods_depressed, mods_latched, mods_locked, 0, 0, group);
}

static void
mg__wl_keyboard_repeat_info(MG_UNUSED void *data,
		MG_UNUSED struct wl_keyboard *wl_keyboard,
		MG_UNUSED int32_t rate,
		MG_UNUSED int32_t delay)
{
	/* stub */
}

static const struct wl_keyboard_listener mg__wl_keyboard_listener = {
	.keymap = mg__wl_keyboard_keymap,
	.enter = mg__wl_keyboard_enter,
	.leave = mg__wl_keyboard_leave,
	.key = mg__wl_keyboard_key,
	.modifiers = mg__wl_keyboard_modifiers,
	.repeat_info = mg__wl_keyboard_repeat_info,
};

static void
mg__wl_buffer_release(MG_UNUSED void *data, struct wl_buffer *wl_buffer)
{
	/* sent by the compositor when it's no longer using this buffer */
	wl_buffer_destroy(wl_buffer);
}

static const struct wl_buffer_listener mg__wl_buffer_listener = {
	.release = mg__wl_buffer_release,
};

static struct wl_buffer *
mg__draw_frame(struct mg__state *mg_state)
{
	size_t stride = (size_t)mg_width * 4;
	size_t size = stride * (size_t)mg_height;

	int fd = mg__allocate_shm_file(size);
	uint32_t *data;
	struct wl_shm_pool *pool;
	struct wl_buffer *buffer;

	if (fd == -1)
		return NULL;

	/*
	 * notice the MAP_SHARED flag. this is because we (obviously)
	 * want others to be able to read the contents of data
	 */
	data = mmap(NULL, size, PROT_READ | PROT_WRITE, MAP_SHARED, fd, 0);
	if (data == MAP_FAILED) {
		close(fd);
		MG__ERROR(MG_OUT_OF_MEMORY)
	}

	/* create a wayland buffer object */
	pool = wl_shm_create_pool(mg_state->wl_shm, fd, (int32_t)size);
	buffer = wl_shm_pool_create_buffer(pool, 0, (int32_t)mg_width, (int32_t)mg_height,
			(int32_t)stride, WL_SHM_FORMAT_XRGB8888);
	wl_shm_pool_destroy(pool);
	close(fd);

	memcpy(data, mg_state->draw_buf, mg_state->buf_size);

	munmap(data, size);
	wl_buffer_add_listener(buffer, &mg__wl_buffer_listener, NULL);
	return buffer;
}

static void
mg__xdg_toplevel_configure(void *data, MG_UNUSED struct xdg_toplevel *xdg_toplevel,
		int32_t width, int32_t height, MG_UNUSED struct wl_array *states)
{
	struct mg__state *mg_state = (struct mg__state *)data;

	if (width == 0 || height == 0)
		/* compositor is deferring to us */
		return;

	if (width != (int32_t)mg_width || height != (int32_t)mg_height) {
		/* draw_buf needs resizing */
		size_t stride, size;
		uint32_t *new_draw_buf;

		mg_width = width;
		mg_height = height;
		stride = (size_t)mg_width * 4;
		size = stride * (size_t)mg_height;

		if (!(new_draw_buf = calloc(size, 1)))
			MG__ERROR(MG_OUT_OF_MEMORY)
		mg__frametrimcpy(new_draw_buf, mg_state->draw_buf,
			mg_state->buf_width, (size_t)mg_width,
			mg_state->buf_stride, stride,
			mg_state->buf_height, (size_t)mg_height);
		free(mg_state->draw_buf);
		mg_state->draw_buf = new_draw_buf;
		mg_state->buf_width = (size_t)mg_width;
		mg_state->buf_stride = stride;
		mg_state->buf_height = (size_t)mg_height;
		mg_state->buf_size = stride * (size_t)mg_height;

		mg_state->pending_resize = 1;
	}
}

static void
mg__xdg_toplevel_close(void *data, MG_UNUSED struct xdg_toplevel *toplevel)
{
	struct mg__state *mg_state = (struct mg__state *)data;
	mg_state->pending_quit = 1;
}

static const struct xdg_toplevel_listener mg__xdg_toplevel_listener = {
	.configure = mg__xdg_toplevel_configure,
	.close = mg__xdg_toplevel_close,
};

static void
mg__xdg_surface_configure(void *data, struct xdg_surface *xdg_surface, uint32_t serial)
{
	struct mg__state *mg_state = (struct mg__state *)data;
	struct wl_buffer *buffer;
	++mg_state->configured;
	xdg_surface_ack_configure(xdg_surface, serial);

	buffer = mg__draw_frame(mg_state);
	wl_surface_attach(mg_state->wl_surface, buffer, 0, 0);
	wl_surface_commit(mg_state->wl_surface);
}

static const struct xdg_surface_listener mg__xdg_surface_listener = {
	.configure = mg__xdg_surface_configure,
};

static void
mg__xdg_wm_base_ping(MG_UNUSED void *data, struct xdg_wm_base *xdg_wm_base, uint32_t serial)
{
	xdg_wm_base_pong(xdg_wm_base, serial);
}

static const struct xdg_wm_base_listener mg__xdg_wm_base_listener = {
	.ping = mg__xdg_wm_base_ping,
};

static void
mg__wl_seat_capabilities(void *data, MG_UNUSED struct wl_seat *wl_seat, uint32_t capabilities)
{
	struct mg__state *mg_state = (struct mg__state *)data;
	int have_keyboard;

	int have_pointer = capabilities & WL_SEAT_CAPABILITY_POINTER;

	if (have_pointer && mg_state->wl_pointer == NULL) {
		mg_state->wl_pointer = wl_seat_get_pointer(mg_state->wl_seat);
		wl_pointer_add_listener(mg_state->wl_pointer,
				&mg__wl_pointer_listener, mg_state);
	} else if (!have_pointer && mg_state->wl_pointer != NULL) {
		wl_pointer_release(mg_state->wl_pointer);
		mg_state->wl_pointer = NULL;
	}

	have_keyboard = capabilities & WL_SEAT_CAPABILITY_KEYBOARD;

	if (have_keyboard && mg_state->wl_keyboard == NULL) {
		mg_state->wl_keyboard = wl_seat_get_keyboard(mg_state->wl_seat);
		wl_keyboard_add_listener(mg_state->wl_keyboard,
				&mg__wl_keyboard_listener, mg_state);
	} else if (!have_keyboard && mg_state->wl_keyboard != NULL) {
		wl_keyboard_release(mg_state->wl_keyboard);
		mg_state->wl_keyboard = NULL;
	}
}

static void
mg__wl_seat_name(MG_UNUSED void *data, MG_UNUSED struct wl_seat *wl_seat, MG_UNUSED const char *name)
{
	/* stub */
}

static const struct wl_seat_listener mg__wl_seat_listener = {
	.capabilities = mg__wl_seat_capabilities,
	.name = mg__wl_seat_name,
};

static void
mg__registry_global(void *data, struct wl_registry *wl_registry, uint32_t name,
		const char *interface, MG_UNUSED uint32_t version)
{
	struct mg__state *mg_state = (struct mg__state *)data;
	if (strcmp(interface, wl_shm_interface.name) == 0) {
		mg_state->wl_shm = wl_registry_bind(
				wl_registry, name, &wl_shm_interface, 1);
	} else if (strcmp(interface, wl_compositor_interface.name) == 0) {
		mg_state->wl_compositor = wl_registry_bind(
				wl_registry, name, &wl_compositor_interface, 4);
	} else if (strcmp(interface, xdg_wm_base_interface.name) == 0) {
		mg_state->xdg_wm_base = wl_registry_bind(
				wl_registry, name, &xdg_wm_base_interface, 1);
		xdg_wm_base_add_listener(mg_state->xdg_wm_base,
				&mg__xdg_wm_base_listener, mg_state);
	} else if (strcmp(interface, wl_seat_interface.name) == 0) {
		mg_state->wl_seat = wl_registry_bind(
				wl_registry, name, &wl_seat_interface, 7);
		wl_seat_add_listener(mg_state->wl_seat,
				&mg__wl_seat_listener, mg_state);
	}
}

static void
mg__registry_global_remove(MG_UNUSED void *data, MG_UNUSED struct wl_registry *wl_registry,
		MG_UNUSED uint32_t name)
{
	/* stub */
}

static const struct wl_registry_listener wl_registry_listener = {
	.global = mg__registry_global,
	.global_remove = mg__registry_global_remove,
};

/* initialization, shutdown, and errors */
void
mg_init(int w, int h, const char *title, jmp_buf err_return)
{
	mg.configured = 0;
	mg.closed = 0;

	/* remember we're using XRGB */
	mg.bgcolor = 0x00FFFFFF;
	mg.color = 0x00000000;

	mg_width = w;
	mg_height = h;
	mg.buf_width = (size_t)mg_width;
	mg.buf_height = (size_t)mg_height;
	mg.buf_stride = mg.buf_width * 4;
	mg.buf_size = mg.buf_stride * mg.buf_height;

	*mg.err_return = *err_return;

	if (!(mg.draw_buf = calloc(mg.buf_size, 1)))
		MG__ERROR(MG_OUT_OF_MEMORY)

	mg.pending_quit = 0;
	mg.pending_resize = 0;
	mg.pending_key_down = 0;
	mg.pending_key_up = 0;
	mg.pending_mouse_down = MG_MOUSE_NO_BUTTON;
	mg.pending_mouse_up = MG_MOUSE_NO_BUTTON;
	mg.pending_mouse_motion_x = -1;
	mg.pending_mouse_motion_y = -1;

	if (!(mg.wl_display = wl_display_connect(NULL)))
		MG__ERROR(MG_INIT_FAILED)

	mg.wl_registry = wl_display_get_registry(mg.wl_display);
	mg.xkb_context = xkb_context_new(XKB_CONTEXT_NO_FLAGS);
	wl_registry_add_listener(mg.wl_registry, &wl_registry_listener, &mg);
	wl_display_roundtrip(mg.wl_display);

	mg.wl_surface = wl_compositor_create_surface(mg.wl_compositor);
	mg.xdg_surface = xdg_wm_base_get_xdg_surface(
			mg.xdg_wm_base, mg.wl_surface);
	xdg_surface_add_listener(mg.xdg_surface, &mg__xdg_surface_listener, &mg);
	mg.xdg_toplevel = xdg_surface_get_toplevel(mg.xdg_surface);
	xdg_toplevel_add_listener(mg.xdg_toplevel,
			&mg__xdg_toplevel_listener, &mg);
	xdg_toplevel_set_title(mg.xdg_toplevel, title);
	wl_surface_commit(mg.wl_surface);

	while (mg.configured < 2)
		wl_display_dispatch(mg.wl_display);
}

const char *
mg_strerror(enum mg_error err)
{
	return mg__strerrors[err];
}

void
mg_quit(void)
{
	if (!mg.closed) {
		free(mg.draw_buf);
		mg.draw_buf = NULL;

		wl_surface_attach(mg.wl_surface, NULL, 0, 0);
		wl_surface_commit(mg.wl_surface);
		wl_surface_destroy(mg.wl_surface);
		xdg_surface_destroy(mg.xdg_surface);
		xdg_toplevel_destroy(mg.xdg_toplevel);
		xdg_wm_base_destroy(mg.xdg_wm_base);
		wl_display_disconnect(mg.wl_display);
		mg.closed = 1;
	}
}

/* events */
int
mg_getevent(struct mg_event *event)
{
	while (wl_display_prepare_read(mg.wl_display) < 0)
		wl_display_dispatch_pending(mg.wl_display);

	wl_display_flush(mg.wl_display);
	wl_display_read_events(mg.wl_display);
	wl_display_dispatch_pending(mg.wl_display);
	return mg__handle_wl_event(event);
}

void
mg_waitevent(struct mg_event *event)
{
	for (;;) {
		/* wait for a wayland event to happen */
		wl_display_dispatch(mg.wl_display);

		/* handle event */
		if (mg__handle_wl_event(event))
			break;
	}
}

/* drawing functions */
void
mg_clear(void)
{
	size_t i = 0;
	for (; i < mg.buf_width * mg.buf_height; ++i)
		mg.draw_buf[i] = mg.bgcolor;
}

void
mg_drawcircle(int x, int y, int r)
{
	int dx = -r, dy = 0, err = 2 - 2 * r;
	do {
		MG__PIXELSET(x - dx, y + dy);
		MG__PIXELSET(x - dy, y - dx);
		MG__PIXELSET(x + dx, y - dy);
		MG__PIXELSET(x + dy, y + dx);

		r = err;
		if (r <= dy)
			err += ++dy * 2 + 1;
		if (r > dx || err > dy)
			err += ++dx * 2 + 1;
	} while (dx < 0);
}

void
mg_drawline(int x1, int y1, int x2, int y2)
{
	x1 = mg__clamp(x1, 0, (int)mg.buf_width - 1);
	y1 = mg__clamp(y1, 0, (int)mg.buf_height - 1);
	x2 = mg__clamp(x2, 0, (int)mg.buf_width - 1);
	y2 = mg__clamp(y2, 0, (int)mg.buf_height - 1);
	if (x1 == x2) {
		int lowy = MG__MIN(y1, y2);
		int highy = MG__MAX(y1, y2);
		for (; lowy <= highy; ++lowy)
			MG__PIXELSET_NOBOUNDSCHECK(x1, lowy);
	} else if (y1 == y2) {
		int lowx = MG__MIN(x1, x2);
		int highx = MG__MAX(x1, x2);
		for (; lowx <= highx; ++lowx)
			MG__PIXELSET_NOBOUNDSCHECK(lowx, y1);
	} else {
		int dx = abs(x2 - x1), sx = (x1 < x2) ? 1 : -1;
		int dy = -abs(y2 - y1), sy = (y1 < y2) ? 1 : -1;
		int err = dx + dy, e2;

		for (;;) {
			MG__PIXELSET_NOBOUNDSCHECK(x1, y1);
			if (x1 == x2 && y1 == y2)
				break;
			e2 = err * 2;
			if (e2 >= dy) {
				err += dy;
				x1 += sx;
			}
			if (e2 <= dx) {
				err += dx;
				y1 += sy;
			}
		}
	}
}

void
mg_drawpixel(int x, int y)
{
	MG__PIXELSET(x, y);
}

void
mg_drawrect(int x1, int y1, int x2, int y2)
{
	mg_drawline(x1, y1, x2, y1); /* top */
	mg_drawline(x2, y1, x2, y2); /* right */
	mg_drawline(x1, y2, x2, y2); /* bottom */
	mg_drawline(x1, y1, x1, y2); /* left */
}

void
mg_drawtext(int x, int y, const char *text, int size)
{
	if (size < 1) {
		return;
	} else {
		size_t i;
		int px, py; /* point x, point y */
		int dx = x; /* draw x */

		for (i = 0; i < strlen(text); ++i) {
			for (py = 0; py < 8; ++py) {
				for (px = 0; px < 8; ++px) {
					if (text[i] >= 0x20 && text[i] <= 0x7e &&
							(mg__font[text[i] - 0x20][py] & 1 << px)) {
						int tmpx = dx + (px * size);
						int tmpy = y + (py * size);
						if (size > 1)
							mg_fillrect(tmpx, tmpy, tmpx + size - 1, tmpy + size - 1);
						else
							MG__PIXELSET(tmpx, tmpy);
					}
				}
			}
			dx += 8 * size;
		}
	}
}

void
mg_drawtriangle(int x1, int y1, int x2, int y2, int x3, int y3)
{
	mg_drawline(x1, y1, x2, y2);
	mg_drawline(x2, y2, x3, y3);
	mg_drawline(x3, y3, x1, y1);
}

void
mg_fillcircle(int x, int y, int r)
{
	/* TODO: this is really bad.... */
	int dx, dy = -r;
	for (; dy <= r; ++dy)
		for (dx = -r; dx <= r; ++dx)
			if (dx * dx + dy * dy < r * r + r)
				MG__PIXELSET(dx + x, dy + y);
}

void
mg_fillrect(int x1, int y1, int x2, int y2)
{
	int x;
	int lowx = mg__clamp(MG__MIN(x1, x2), 0, (int)mg.buf_width - 1);
	int highx = mg__clamp(MG__MAX(x1, x2), 0, (int)mg.buf_width - 1);
	int lowy = mg__clamp(MG__MIN(y1, y2), 0, (int)mg.buf_height - 1);
	int highy = mg__clamp(MG__MAX(y1, y2), 0, (int)mg.buf_height - 1);

	for (; lowy <= highy; ++lowy)
		for (x = lowx; x <= highx; ++x)
			MG__PIXELSET_NOBOUNDSCHECK(x, lowy);
}

void
mg_filltriangle(int x1, int y1, int x2, int y2, int x3, int y3)
{
	/*
	 * see http://www.sunshine2k.de/coding/java/TriangleRasterization/TriangleRasterization.html
	 * for the algorithm used here
	 */
	int nx1, ny1, nx2, ny2, nx3, ny3;
	mg__sort_ascending_by_y(x1, y1, x2, y2, x3, y3, &nx1, &ny1, &nx2, &ny2, &nx3, &ny3);
	/* now we can assume that ny1 <= ny2 <= ny3 */

	if (ny2 == ny3) {
		/* bottom-flat triangle */
		mg__fillflatsidetriangle(nx1, ny1, nx2, ny2, nx3, ny3);
	} else if (ny1 == ny2) {
		/* top-flat triangle */
		mg__fillflatsidetriangle(nx3, ny3, nx1, ny1, nx2, ny2);
	} else {
		/* split triangle into top-flat && bottom-flat */
		int tmp = (int)((float)nx1 + ((float)(ny2 - ny1) / (float)(ny3 - ny1)) * (float)(nx3 - nx1));
		mg__fillflatsidetriangle(nx1, ny1, nx2, ny2, tmp, ny2);
		mg__fillflatsidetriangle(nx3, ny3, nx2, ny2, tmp, ny2);
	}
}

void
mg_flush(void)
{
	/* submit a frame for this event */
	if (!mg.closed) {
		struct wl_buffer *buffer = mg__draw_frame(&mg);
		wl_surface_attach(mg.wl_surface, buffer, 0, 0);
		wl_surface_damage_buffer(mg.wl_surface, 0, 0, INT32_MAX, INT32_MAX);
		wl_surface_commit(mg.wl_surface);
	}
}

/* images */
struct mg_image *
mg_image_create(uint8_t *data, uint32_t width, uint32_t height)
{
	if (width == 0 || height == 0) {
		return NULL;
	} else {
		struct mg_image *img = malloc(sizeof(struct mg_image));
		if (!img)
			MG__ERROR(MG_OUT_OF_MEMORY)

		img->data = malloc(width * height * 3);
		if (!img->data)
			MG__ERROR(MG_OUT_OF_MEMORY)

		memcpy(img->data, data, width * height * 3);
		img->width = width;
		img->height = height;
		return img;
	}
}

void
mg_image_draw(struct mg_image *image, int x, int y)
{
	if (!image)
		return;

	if (x < (int)mg.buf_width && y < (int)mg.buf_height) {
		size_t i = 0; /* position in image buffer */
		int dx, dy = 0; /* x offset / y offset to draw at */
		for (; dy < (int)image->height; ++dy) {
			for (dx = 0; dx < (int)image->width; ++dx) {
				if ((dx + x) >= 0 && (dy + y) >= 0 && (dx + x) < (int)mg.buf_width &&
						(dy + y) < (int)mg.buf_height) {
					/* remember we're using XRGB */
					mg.draw_buf[(dy + y) * (int)mg.buf_width + (dx + x)] = (uint32_t)
						((image->data[i] << 16) | (image->data[i + 1] << 8) |
						 image->data[i + 2]);
				}
				i += 3;
			}
		}
	}
}

void
mg_image_free(struct mg_image *image)
{
	if (!image)
		return;

	free(image->data);
	free(image);
}

/* functions to set colors */
void
mg_setbgcolor(uint8_t r, uint8_t g, uint8_t b)
{
	/* remember we're using XRGB */
	mg.bgcolor = (uint32_t)((r << 16) | (g << 8) | b);
}

void
mg_setdrawcolor(uint8_t r, uint8_t g, uint8_t b)
{
	/* remember we're using XRGB */
	mg.color = (uint32_t)((r << 16) | (g << 8) | b);
}
#endif /* defined(MG_BACKEND_WAYLAND) */

#endif /* MG_IMPLEMENTATION */

/*
 * This library is available under 2 licenses - choose whichever you prefer.
 *
 * ---------------------------------------------------------------------------
 * ALTERNATIVE A - MIT/X Consortium License
 *
 * Copyright (c) 2024 iusevoidbtw
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 * ---------------------------------------------------------------------------
 * ALTERNATIVE B - Unlicense
 *
 * This is free and unencumbered software released into the public domain.
 *
 * Anyone is free to copy, modify, publish, use, compile, sell, or
 * distribute this software, either in source code form or as a compiled
 * binary, for any purpose, commercial or non-commercial, and by any
 * means.
 *
 * In jurisdictions that recognize copyright laws, the author or authors
 * of this software dedicate any and all copyright interest in the
 * software to the public domain. We make this dedication for the benefit
 * of the public at large and to the detriment of our heirs and
 * successors. We intend this dedication to be an overt act of
 * relinquishment in perpetuity of all present and future rights to this
 * software under copyright law.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 * IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
 * OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 *
 * For more information, please refer to <http://unlicense.org/>
 */
